- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Docker Container
      docker_container:
        name: project-demo
        image: kadururohith/project-demo:1
        state: started
        ports:
          - "8084:8081"

    


